{% set version = "1.0.0" %}

package:
  name: mfdurbansim
  version: {{ version }}

source:
  path: ../

build:
  noarch: python
  number: 0
  script: python -m pip install . -vvv

requirements:
  host:
    - python
    - pip
  run:
    - python
    - pandas
    - numpy
    - matplotlib

test:
  imports:
    - mfdurbansim

about:
  home: https://github.com/licit-lab/MFDurbanSim
  license_file: LICENSE
  dev_url: https://github.com/licit-lab/MFDurbanSim
  doc_url: https://github.com/licit-lab/MFDurbanSim
  doc_source_url: https://github.com/licit-lab/MFDurbanSim/blob/master/README.md